sudo: false

language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.cache"

before_install:
  - cp .travis.settings.xml ~/.m2/settings.xml

deploy:
  provider: script
  script: "mvn deploy"
  skip_cleanup: true

after_script:
  - ./copy2media.sh
