sudo: false

language: java

jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.cache"

before_install:
  - cp maven.settings.xml ~/.m2/settings.xml
  - curl -i http://developer.dev404.net/maven/

deploy:
  provider: script
  script: "mvn -X deploy"
  skip_cleanup: true

after_script:
  - ./copy2media.sh
